version: "3.8"

networks:
  corp:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: ./
      cache_from:
        - portfolio-base-image:nx-base
      dockerfile: ./apps/api/Dockerfile
    image: api:nx-prod
    ports:
      - 3333:3333
    networks:
      - corp
    restart: on-failure

  ng-portfolio:
    container_name: ng-portfolio
    build:
      context: ./
      cache_from:
        - nginx:1.23.3-alpine
      dockerfile: ./apps/ng-portfolio/Dockerfile
    image: ng-portfolio:nx-prod
    ports:
      - 4900:80
    networks:
      - corp
    restart: on-failure